name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Print user
      run: whoami

    - name: Install dependencies
      run: sudo npm ci

    - name: Run tests
      run: sudo npm test
